const add = require("./math")
const name = require("./greet")
const object = require("./object")
const {addTwoNumber,duble} = require("./twoFunction")
const {addNumber,sub,multiple} = require("./utils")
const even = require("./even")
const Class = require("./class")
const getArray = require("./array")
const addEven = require("./advanceMath")
console.log(add(5,7))
console.log(name("david"))
console.log(object.name,object.age)
console.log(addTwoNumber(5,7),duble(3,4))
console.log(addNumber(5,7),sub(7,3),multiple(4,4))
console.log(even(4))
console.log(even(5))
console.log(even(6))
const user = new Class("david")
console.log(user.name)
console.log(getArray.reduce((acc,current) => acc + current, 0))
console.log(addEven(4,6))

